// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import "fyne.io/fyne/v2"

var resourceLogoSvg = &fyne.StaticResource{
	StaticName: "logo.svg",
	StaticContent: []byte(
		"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n\r<!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->\n<svg width=\"800px\" height=\"800px\" viewBox=\"0 0 20 20\" xmlns=\"http://www.w3.org/2000/svg\">\n\r<rect x=\"0\" fill=\"none\" width=\"20\" height=\"20\"/>\n\r<g>\n\r<path d=\"M13.23 15h1.9L11 4H9L5 15h1.88l1.07-3h4.18zm-1.53-4.54H8.51L10 5.6z\"/>\n\r</g>\n\r</svg>"),
}
